export default {
  "7z": "application/x-7z-compressed",
  atom: "application/atom+xml",
  bin: "application/octet-stream",
  bz2: "application/x-bzip2",
  gz: "application/gzip",
  json: "application/json",
  jsonld: "application/ld+json",
  map: "application/json",
  pdf: "application/pdf",
  rar: "application/x-rar-compressed",
  rss: "application/rss+xml",
  tar: "application/x-tar",
  wasm: "application/wasm",
  webmanifest: "application/manifest+json",
  xml: "application/xml",
  yaml: "application/yaml",
  yml: "application/yaml",
  zip: "application/zip",

  mp3: "audio/mpeg",
  ogg: "audio/ogg",
  wav: "audio/wav",
  weba: "audio/webm",

  otf: "font/otf",
  ttf: "font/ttf",
  woff: "font/woff",
  woff2: "font/woff2",

  apng: "image/apng",
  avif: "image/avif",
  bmp: "image/bmp",
  gif: "image/gif",
  ico: "image/x-icon",
  jpeg: "image/jpeg",
  jpg: "image/jpeg",
  png: "image/png",
  svg: "image/svg+xml",
  tif: "image/tiff",
  tiff: "image/tiff",
  webp: "image/webp",

  css: "text/css",
  csv: "text/csv",
  htm: "text/html",
  html: "text/html",
  js: "text/javascript",
  md: "text/markdown",
  markdown: "text/markdown",
  mjs: "text/javascript",
  rtf: "text/rtf",
  text: "text/plain",
  tsv: "text/tab-separated-values",
  txt: "text/plain",
  vtt: "text/vtt",

  mov: "video/quicktime",
  mp4: "video/mp4",
  ogv: "video/ogg",
  ts: "video/mp2t",
  webm: "video/webm",
} as const;
